### ISSUE TITLE
Missing or invalid attribute 'comment' on Windows IDA 7.6

### ISSUE THREAD

**Issue by caprinux** [mahaloz/decomp2gef#11]
IDA version 7.6 
Python 3.10

decomp2gef ida script seems to fail at `Z:\...\IDA\IDA Pro 7.6\plugins\decomp2gef_ida.py: Missing or invalid attribute 'comment'` and I seem to be unable to see the decomp2gef plugin being loaded successfully. any ideas?

```
  bytes   pages size description
--------- ----- ---- --------------------------------------------
   532480    65 8192 allocating memory for b-tree...
   507904    62 8192 allocating memory for virtual array...
   262144    32 8192 allocating memory for name pointers...
-----------------------------------------------------------------
  1302528            total memory allocated

Loading processor module Z:\...\IDA\IDA Pro 7.6\procs\pc.dll for metapc...Initializing processor module metapc...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
Z:\...\IDA\IDA Pro 7.6\plugins\decomp2gef_ida.py: Missing or invalid attribute 'comment'
Database for file 'redacted' has been loaded.
Hex-Rays Decompiler plugin has been loaded (v7.6.0.210427)
  License: 57-631C-7A2B-72 IDA PRO 7.6 SP1 (99 users)
  The hotkeys are F5: decompile, Ctrl-F5: decompile all.

  Please check the Edit/Plugins menu for more informaton.
Z:\...\IDA\IDA Pro 7.6\plugins\decomp2gef_ida.py: Missing or invalid attribute 'comment'
805EF50: restored microcode from idb
805EF50: restored pseudocode from idb
-----------------------------------------------------------------------------------------
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] 
IDAPython v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
-----------------------------------------------------------------------------------------
```

**Comment by mahaloz** [comment]
@caprinux Alright, after some flimsy investigating it appears this is either an IDA issue or a PyQT5 issue, I think the latter. Check out this link: https://www.techbliss.org/threads/ida-pro-7-0-pyqt5-total-package-by-storm-shadow.950/. 

From what I can tell, I think it is a PyQT5 issue on Windows.

**Comment by mahaloz** [comment]
@caprinux I also have an alternative theory that Python3.10 is not sitting well with PyQT5 (which is what I use for the GUI). It is strange, since I thought IDA was QT5. If you want to try something that may or may not work, try replacing all the strings "PyQT5" in the python file with "PySide2" and make sure to have it installed.

**Comment by caprinux** [comment]
This is rather intriguing, I've been digging into it based on your findings and it seems to be prevalent across python 3.8 - 3.10. 

Beyond that, IDA doesn't seem to offer support for python versions between 3.4 to 3.8, and python 3.4 is not supported by the decomp2gef script.

PySide2 seems to break even more than PyQT so that's a nogo as well. 

I do agree it seems to be a PyQt issue but I still haven't been able to find a fix as of yet. The prior links provided to the forum only had files for python 2.7 which is once again insufficient. 

I'll dig more into it and see what I can find

**Comment by willinin** [comment]
delete code about GUI and run.

**Comment by mahaloz** [comment]
@caprinux 
> This is rather intriguing, I've been digging into it based on your findings and it seems to be prevalent across python 3.8 - 3.10. 

On MacOS and Linux Python version 3.9.7 works fine, so this must be a Windows specific issue still. 

> delete code about GUI and run. 

If this becomes an issue for many people, I can add some way to do this all over the command prompt in IDA... it will just be a little complicated hehe.

**Comment by caprinux** [comment]
I removed the entire code regarding the GUI and hardcoded the server and port — exact same error appears!!

This means even without touching the PyQt package as a whole, it still appears to break. This is honestly such a big mystery to me at the moment and I can't seem to figure out where this mysterious **comment** attribute is referenced.

I decided to attach a remote python debugger at the start of the decomp2gef_ida.py script and step into every single function. I will attach the entire output at the bottom fo this comment. 

Although I did not encounter any 'comment' attribute throughout my run, I still got `Missing or invalid attribute 'comment'` error.

Something noticeable through my run was the missing attribute 'this' within IDBHooks().

![image](https://user-images.githubusercontent.com/76640319/148638154-229bce6d-e066-4d2a-8512-ff107388c7b1.png)

Anyone has any ideas?

Here's the entire log:

```py
> z:\home\cap\downloads\stuff\ida pro 7.6\plugins\decomp2gef_ida.py(6)PLUGIN_ENTRY()
-> return Decomp2GEFPlugin(*args, **kwargs)
(Pdb) s
--Call--
> z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(83)__init__()
-> def __init__(self, *args, **kwargs):
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(84)__init__()
-> idaapi.plugin_t.__init__(self)
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(85)__init__()
-> self.change_hook = IDBHooks()
(Pdb) 
--Call--
> z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(13)__init__()
-> def __init__(self):
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(14)__init__()
-> ida_idp.IDB_Hooks.__init__(self)
(Pdb) 
--Call--
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4675)__init__()
-> def __init__(self, *args):
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4682)__init__()
-> if self.__class__ == IDB_Hooks:
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4685)__init__()
-> _self = self
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4686)__init__()
-> _ida_idp.IDB_Hooks_swiginit(self, _ida_idp.new_IDB_Hooks(_self, *args))
(Pdb) 
--Call--
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(26)_swig_repr()
-> def _swig_repr(self):
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(27)_swig_repr()
-> try:
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(28)_swig_repr()
-> strthis = "proxy of " + self.this.__repr__()
(Pdb) 
AttributeError: 'IDBHooks' object has no attribute 'this'
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(28)_swig_repr()
-> strthis = "proxy of " + self.this.__repr__()
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(29)_swig_repr()
-> except __builtin__.Exception:
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(30)_swig_repr()
-> strthis = ""
(Pdb) 
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(31)_swig_repr()
-> return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)
(Pdb) 
--Return--
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(31)_swig_repr()->'<d2g_ida.plugin.IDBHooks;  >'
-> return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)
(Pdb) 
--Return--
> z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4686)__init__()->None
-> _ida_idp.IDB_Hooks_swiginit(self, _ida_idp.new_IDB_Hooks(_self, *args))
(Pdb) 
--Return--
> z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(14)__init__()->None
-> ida_idp.IDB_Hooks.__init__(self)
(Pdb) 
--Return--
> z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(85)__init__()->None
-> self.change_hook = IDBHooks()
(Pdb) 
--Return--
> z:\home\cap\downloads\stuff\ida pro 7.6\plugins\decomp2gef_ida.py(6)PLUGIN_ENTRY()-><d2g_ida.plug...000000D998DF0>
-> return Decomp2GEFPlugin(*args, **kwargs)
(Pdb) 
--Call--

# at this point, IDA has already opened and thrown the 'comment' attribute error t_t

> c:\users\cap\appdata\local\programs\python\python39\lib\threading.py(1384)_shutdown()
-> def _shutdown():
```

**Comment by willinin** [comment]
> I removed the entire code regarding the GUI and hardcoded the server and port — exact same error appears!!
> 
> This means even without touching the PyQt package as a whole, it still appears to break. This is honestly such a big mystery to me at the moment and I can't seem to figure out where this mysterious **comment** attribute is referenced.
> 
> I decided to attach a remote python debugger at the start of the decomp2gef_ida.py script and step into every single function. I will attach the entire output at the bottom fo this comment.
> 
> Although I did not encounter any 'comment' attribute throughout my run, I still got `Missing or invalid attribute 'comment'` error.
> 
> Something noticeable through my run was the missing attribute 'this' within IDBHooks().
> 
> ![image](https://user-images.githubusercontent.com/76640319/148638154-229bce6d-e066-4d2a-8512-ff107388c7b1.png)
> 
> Anyone has any ideas?
> 
> Here's the entire log:
> 
> ```python
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\decomp2gef_ida.py(6)PLUGIN_ENTRY()
> -> return Decomp2GEFPlugin(*args, **kwargs)
> (Pdb) s
> --Call--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(83)__init__()
> -> def __init__(self, *args, **kwargs):
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(84)__init__()
> -> idaapi.plugin_t.__init__(self)
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(85)__init__()
> -> self.change_hook = IDBHooks()
> (Pdb) 
> --Call--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(13)__init__()
> -> def __init__(self):
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(14)__init__()
> -> ida_idp.IDB_Hooks.__init__(self)
> (Pdb) 
> --Call--
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4675)__init__()
> -> def __init__(self, *args):
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4682)__init__()
> -> if self.__class__ == IDB_Hooks:
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4685)__init__()
> -> _self = self
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4686)__init__()
> -> _ida_idp.IDB_Hooks_swiginit(self, _ida_idp.new_IDB_Hooks(_self, *args))
> (Pdb) 
> --Call--
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(26)_swig_repr()
> -> def _swig_repr(self):
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(27)_swig_repr()
> -> try:
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(28)_swig_repr()
> -> strthis = "proxy of " + self.this.__repr__()
> (Pdb) 
> AttributeError: 'IDBHooks' object has no attribute 'this'
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(28)_swig_repr()
> -> strthis = "proxy of " + self.this.__repr__()
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(29)_swig_repr()
> -> except __builtin__.Exception:
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(30)_swig_repr()
> -> strthis = ""
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(31)_swig_repr()
> -> return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(31)_swig_repr()->'<d2g_ida.plugin.IDBHooks;  >'
> -> return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4686)__init__()->None
> -> _ida_idp.IDB_Hooks_swiginit(self, _ida_idp.new_IDB_Hooks(_self, *args))
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(14)__init__()->None
> -> ida_idp.IDB_Hooks.__init__(self)
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(85)__init__()->None
> -> self.change_hook = IDBHooks()
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\decomp2gef_ida.py(6)PLUGIN_ENTRY()-><d2g_ida.plug...000000D998DF0>
> -> return Decomp2GEFPlugin(*args, **kwargs)
> (Pdb) 
> --Call--
> 
> # at this point, IDA has already opened and thrown the 'comment' attribute error t_t
> 
> > c:\users\cap\appdata\local\programs\python\python39\lib\threading.py(1384)_shutdown()
> -> def _shutdown():
> ```



> I removed the entire code regarding the GUI and hardcoded the server and port — exact same error appears!!
> 
> This means even without touching the PyQt package as a whole, it still appears to break. This is honestly such a big mystery to me at the moment and I can't seem to figure out where this mysterious **comment** attribute is referenced.
> 
> I decided to attach a remote python debugger at the start of the decomp2gef_ida.py script and step into every single function. I will attach the entire output at the bottom fo this comment.
> 
> Although I did not encounter any 'comment' attribute throughout my run, I still got `Missing or invalid attribute 'comment'` error.
> 
> Something noticeable through my run was the missing attribute 'this' within IDBHooks().
> 
> ![image](https://user-images.githubusercontent.com/76640319/148638154-229bce6d-e066-4d2a-8512-ff107388c7b1.png)
> 
> Anyone has any ideas?
> 
> Here's the entire log:
> 
> ```python
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\decomp2gef_ida.py(6)PLUGIN_ENTRY()
> -> return Decomp2GEFPlugin(*args, **kwargs)
> (Pdb) s
> --Call--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(83)__init__()
> -> def __init__(self, *args, **kwargs):
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(84)__init__()
> -> idaapi.plugin_t.__init__(self)
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(85)__init__()
> -> self.change_hook = IDBHooks()
> (Pdb) 
> --Call--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(13)__init__()
> -> def __init__(self):
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(14)__init__()
> -> ida_idp.IDB_Hooks.__init__(self)
> (Pdb) 
> --Call--
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4675)__init__()
> -> def __init__(self, *args):
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4682)__init__()
> -> if self.__class__ == IDB_Hooks:
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4685)__init__()
> -> _self = self
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4686)__init__()
> -> _ida_idp.IDB_Hooks_swiginit(self, _ida_idp.new_IDB_Hooks(_self, *args))
> (Pdb) 
> --Call--
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(26)_swig_repr()
> -> def _swig_repr(self):
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(27)_swig_repr()
> -> try:
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(28)_swig_repr()
> -> strthis = "proxy of " + self.this.__repr__()
> (Pdb) 
> AttributeError: 'IDBHooks' object has no attribute 'this'
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(28)_swig_repr()
> -> strthis = "proxy of " + self.this.__repr__()
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(29)_swig_repr()
> -> except __builtin__.Exception:
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(30)_swig_repr()
> -> strthis = ""
> (Pdb) 
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(31)_swig_repr()
> -> return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(31)_swig_repr()->'<d2g_ida.plugin.IDBHooks;  >'
> -> return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\python\3\ida_idp.py(4686)__init__()->None
> -> _ida_idp.IDB_Hooks_swiginit(self, _ida_idp.new_IDB_Hooks(_self, *args))
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(14)__init__()->None
> -> ida_idp.IDB_Hooks.__init__(self)
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\d2g_ida\plugin.py(85)__init__()->None
> -> self.change_hook = IDBHooks()
> (Pdb) 
> --Return--
> > z:\home\cap\downloads\stuff\ida pro 7.6\plugins\decomp2gef_ida.py(6)PLUGIN_ENTRY()-><d2g_ida.plug...000000D998DF0>
> -> return Decomp2GEFPlugin(*args, **kwargs)
> (Pdb) 
> --Call--
> 
> # at this point, IDA has already opened and thrown the 'comment' attribute error t_t
> 
> > c:\users\cap\appdata\local\programs\python\python39\lib\threading.py(1384)_shutdown()
> -> def _shutdown():
> ```

I read code about ida genmc(microcode about) plugins  and do patch as follow (it work well in windows):

class Decomp2GEFPlugin(idaapi.plugin_t):
    """Plugin entry point. Does most of the skinning magic."""
    # flags = 0
    # comment = "Display microcode"
    # help = comment
    # wanted_name = PLUGIN_NAME
    # wanted_hotkey = "Ctrl-Shift-M"
    #flags = idaapi.PLUGIN_FIX
    flags = 0
    comment = "Display microcode"
    help = comment
    wanted_name = "Decomp2GEF: configure"
    wanted_hotkey = "Ctrl-Shift-D"

    def __init__(self, *args, **kwargs):
        #QObject.__init__(self, *args, **kwargs)
        idaapi.plugin_t.__init__(self)
        self.change_hook = IDBHooks()

    def init(self):
        #return idaapi.PLUGIN_KEEP
        return idaapi.PLUGIN_OK

    def run(self, arg):
        self.open_config_dialog()

    def open_config_dialog(self):
        global decomp_server
        decomp_server = IDADecompilerServer()
        t = threading.Thread(target=decomp_server.start_xmlrpc_server, kwargs={'host': "0.0.0.0", 'port': int(3662)})
        t.daemon = True
        #print("debug!")
        try:
            t.start()
            # start hooks on good connection
            self.change_hook.hook()
        except Exception as e:
            #QMessageBox(self).critical(None, "Error starting Decomp2GEF Server", str(e))
            #traceback.print_exc()
            return
        #print("debug2!")
        #dialog = ConfigDialog(self.change_hook)
        #dialog.exec_()

**Comment by mahaloz** [comment]
@caprinux @willinin
I'm kinda an idiot. The issue was looking me right in the face. I am amazed that this bug is not triggered on Linux or MacOS. Please pull main now and try the plugin again. I made sure `comment` and `help` were defined in the plugin constants now, so it should work. The problem was addressed in #12.

Lmk if it works so I can close the issue :).

**Comment by caprinux** [comment]
@mahaloz Works like a charm! Thanks :)

**Comment by mahaloz** [comment]
wonderful @caprinux! Thanks for reporting!
