### ISSUE TITLE
invalid string offset for section `.strtab'

### ISSUE THREAD

**Issue by caprinux** [mahaloz/decomp2gef#14]
When connecting GEF to the decompiler, gdb fails to add-symbol-file and throws an error. 

`BFD: /tmp/tmp3pmay68f.c.debug: invalid string offset 16777215 >= 282 for section '.strtab'`

Although this does not break decomp2gef, it causes the debugger to be without a symbol file and hence renders some features unusable.

Sample binary with this behavior: 
[sample_program.zip](https://github.com/mahaloz/decomp2gef/files/7838699/sample_program.zip)

**Comment by mahaloz** [comment]
Without full triage, I think this may be related to #15. Will resolve #15 first then circle back to this.

**Comment by mahaloz** [comment]
So it appears that this issue has reappeared even with your patch on x64 binaries now

**Comment by mahaloz** [comment]
On main `BFD: /tmp/tmpdyamth15.c.debug: invalid string offset 16777215 >= 3280 for section `.strtab'` is now back for `beanstalk` binary... and objdump for reference. @caprinux

**Comment by caprinux** [comment]
@mahaloz That's weird, I can't seem to reproduce this from the decomp2gef master branch. Beanstalk works perfectly fine for me... Any steps to reproduce or any clues I can work off?

**Comment by mahaloz** [comment]
@caprinux turns out I goofed. Let's finish up #21, then close.

**Comment by mahaloz** [comment]
closed by #21
