### ISSUE TITLE
add instruction for wsl2

### ISSUE THREAD

**Issue by RoderickChan** [mahaloz/decomp2gef#29]
I suggest to add instruction for those who want to use this tool in wsl. 

1. run `./install.sh --ida /mnt/c/xxx/IDA/plugins` to install
2. listen to 0.0.0.0:3662 in IDA
3. add an `Inbound Rules` for port 3662 in Windows Firewall, private or domain network
4. run `decompiler connect ida 192.168.xxx.xxx(LAN IP) 3662` in gdb to connect

**Comment by mahaloz** [comment]
@RoderickChan I've added a little snippet to the front about allowing inbound connections. Since this does use networking, it would be a little too cumbersome to describe for each platform how to set up a connection, since the user can change both the IP and port.
